# Generated by Django 5.0 on 2025-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phyla', models.CharField(help_text='Taxonomic phylum', max_length=100)),
                ('genus', models.CharField(blank=True, max_length=100)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('genome_reference_link', models.URLField(blank=True, help_text='Link to genome reference (NCBI or other public database)', null=True)),
                ('age_range', models.CharField(blank=True, help_text='Age range where species is found (e.g., 0-1y, adult)', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
