# Generated by Django 5.0 on 2025-10-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasoBiome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='age_range',
            field=models.CharField(blank=True, help_text='Age range where species is found (e.g., 0-1y, adult)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='body_sites',
            field=models.ManyToManyField(blank=True, help_text='All sites where this species has been detected or migrated to.', related_name='associated_species', to='NasoBiome.bodysite'),
        ),
        migrations.AddField(
            model_name='species',
            name='origin_site',
            field=models.ForeignKey(blank=True, help_text='Primary site where this species normally resides (typically the nose).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nasal_microbes', to='NasoBiome.bodysite'),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mechanism_of_causation', models.TextField(blank=True, help_text='Explain how this disease develops (e.g., due to inflammation, toxin, immune response).')),
                ('affected_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='NasoBiome.bodysite')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='Diseases this species is associated with (directly or through interaction).', related_name='associated_species', to='NasoBiome.disease'),
        ),
        migrations.CreateModel(
            name='MigrationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(blank=True, help_text='Pathway or mechanism of migration (e.g., aspiration, bloodstream, swallowing, inhalation).', max_length=100)),
                ('trigger_conditions', models.TextField(blank=True, help_text='Conditions under which migration occurs (e.g., inflammation, immune suppression).')),
                ('evidence', models.TextField(blank=True, help_text='Supporting literature or experimental evidence (e.g., PubMed links, DOIs, or citations).')),
                ('from_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_from', to='NasoBiome.bodysite')),
                ('resulting_disease', models.ForeignKey(blank=True, help_text='Disease caused directly due to this migration (without interaction).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_caused_diseases', to='NasoBiome.disease')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='NasoBiome.species')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_to', to='NasoBiome.bodysite')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mechanism_of_action', models.TextField(blank=True, help_text='Describe how this product contributes to disease (e.g., toxin-mediated tissue damage, immune modulation).')),
                ('contributes_to', models.ManyToManyField(blank=True, help_text='Diseases where this product plays a pathogenic role.', related_name='product_contributors', to='NasoBiome.disease')),
                ('produced_by', models.ManyToManyField(blank=True, related_name='produced_products', to='NasoBiome.species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Molecular products secreted by this species.', related_name='producing_species', to='NasoBiome.product'),
        ),
        migrations.CreateModel(
            name='SpeciesInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('synergistic', 'Synergistic (enhance each other)'), ('antagonistic', 'Antagonistic (inhibit each other)'), ('neutral', 'Neutral (no clear effect)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('mechanism', models.TextField(blank=True, help_text='Describe how this interaction occurs (e.g., via quorum sensing, metabolite exchange, competition for nutrients).')),
                ('associated_disease', models.ForeignKey(blank=True, help_text='Disease caused as a result of this microbial interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_caused_diseases', to='NasoBiome.disease')),
                ('site', models.ForeignKey(help_text='Site where this interaction occurs (e.g., skin)', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='NasoBiome.bodysite')),
                ('species_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_source', to='NasoBiome.species')),
                ('species_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_target', to='NasoBiome.species')),
            ],
        ),
    ]
