# Generated by Django 5.0 on 2025-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasoBiome', '0002_bodysite_alter_species_age_range_species_body_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationpattern',
            name='produced_products',
            field=models.ManyToManyField(blank=True, help_text='Products secreted by this species during migration to this site.', related_name='produced_during_migration', to='NasoBiome.product'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='mechanism',
            field=models.CharField(blank=True, help_text='Pathway or mechanism of migration (e.g., aspiration, bloodstream, swallowing, inhalation).', max_length=400),
        ),
    ]
