# Generated by Django 5.0 on 2025-10-30 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasoBiome', '0003_migrationpattern_produced_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationpattern',
            name='produced_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contributes_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='produced_by',
        ),
        migrations.RemoveField(
            model_name='speciesinteraction',
            name='description',
        ),
        migrations.AddField(
            model_name='speciesinteraction',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='mechanism_of_causation',
            field=models.TextField(blank=True, help_text='Explain how this disease develops (e.g., inflammation, immune response, toxin).'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='mechanism',
            field=models.CharField(blank=True, help_text='Mechanism (e.g., aspiration, bloodstream).', max_length=400),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='resulting_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_caused_diseases', to='NasoBiome.disease'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='trigger_conditions',
            field=models.TextField(blank=True, help_text='Conditions enabling migration (e.g., inflammation).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanism_of_action',
            field=models.TextField(blank=True, help_text='Describe how this product contributes to disease (e.g., toxin-mediated damage).'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genome_reference_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesinteraction',
            name='associated_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_caused_diseases', to='NasoBiome.disease'),
        ),
        migrations.AlterField(
            model_name='speciesinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('synergistic', 'Synergistic (enhance each other)'), ('antagonistic', 'Antagonistic (inhibit each other)'), ('neutral', 'Neutral (no effect)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='speciesinteraction',
            name='mechanism',
            field=models.TextField(blank=True, help_text='Mechanism (e.g., quorum sensing, metabolite competition).'),
        ),
        migrations.AlterField(
            model_name='speciesinteraction',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='NasoBiome.bodysite'),
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.TextField(blank=True, help_text='How the product is produced (trigger mechanism).')),
                ('evidence', models.TextField(blank=True, help_text='Literature or experimental evidence (DOI, PubMed link).')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causing_events', to='NasoBiome.disease')),
                ('interacting_species', models.ForeignKey(blank=True, help_text='Optional partner species.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_product_events', to='NasoBiome.species')),
                ('interaction', models.ForeignKey(blank=True, help_text='Linked if produced due to interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to='NasoBiome.speciesinteraction')),
                ('migration', models.ForeignKey(blank=True, help_text='Linked if produced during migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to='NasoBiome.migrationpattern')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='NasoBiome.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='NasoBiome.bodysite')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='NasoBiome.species')),
            ],
        ),
    ]
