# Generated by Django 5.0 on 2025-11-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasoBiome', '0004_remove_migrationpattern_produced_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migrationpattern',
            options={'verbose_name': 'Migration Pattern', 'verbose_name_plural': 'Migration Patterns'},
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='from_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations_from', to='NasoBiome.bodysite'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='mechanism',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='resulting_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NasoBiome.disease'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='to_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations_to', to='NasoBiome.bodysite'),
        ),
        migrations.AlterField(
            model_name='migrationpattern',
            name='trigger_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
