# Generated by Django 5.0 on 2025-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasoBiome', '0005_alter_migrationpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationpattern',
            name='mechanism',
            field=models.TextField(blank=True, null=True),
        ),
    ]
